"""
Django settings for gcs_coop project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '20x8^lz%yf#b-s7*9u$88!@c2z!5hhubcz6r-ghn+c#75@7nba'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # The first for standard
    'registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local Apps
    'catalogues',
    'core',
    'coop_info',
    'dashboard',
    'process_coop',
    'pre_register',
    'runway',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gcs_coop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gcs_coop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # srv Dev 1
    # 'default': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'gcscoop',
    #     'USER': 'sa',
    #     'PASSWORD': 'jrojas123',
    #     'HOST': 'localhost',
    #     'PORT': '',
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 13 for SQL Server',
    #     }
    # }

    # srv Dev 2
    # 'default': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'gcscoop',
    #    'USER': 'root',
    #    'PASSWORD': 'Kierovomitar1',
    #    'HOST': 'localhost',
    #    'PORT': ''
    # }

    # # srv Dev 2.1
    #  'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'gcscoop',
    #     'USER': 'zodux',
    #     'PASSWORD': 'Omega*123',
    #     'HOST': 'localhost',
    #     'PORT': ''
    # }

    # srv
    'default': {
       'ENGINE': 'django.db.backends.mysql',
       'NAME': 'gcscoop',
       'USER': 'root',
       'PASSWORD': 'QntmQw3rty#',
       'HOST': '127.0.0.1',
      'PORT': ''
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# Modificamos la ruta de los static para una sola carpeta
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración para pantallas de login y logout
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Email configuration
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'quantumqwrty@gmail.com'
EMAIL_HOST_PASSWORD = 'Pumpumpurin#Makers777'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# STRIPE KEYS
STRIPE_PUBLIC_KEY = 'pk_test_51J8dDBCor9GAAV0ad6MbhgeYe7B84iHhSLGpYQaUJoqimGGqQElosC5q9MI3OjisDEqE92yjQoDuDcE9yqRVklJP00qAgS2FnZ'
STRIPE_SECRET_KEY = 'sk_test_51J8dDBCor9GAAV0ahAXOwdMJMrlKBOSeTV4FsPn2GSsFTPFcXjI31dNdjMshsA9PelV0sYY0lnz0UxNSArqXtckT00AFKdDiAH'
STRIPE_WEBHOOK_SECRET = ''
